[theme]
primaryColor = "#2E7D32"
base = "dark"
backgroundColor = "#131a25"
secondaryBackgroundColor = "#1a2331"
textColor = "#FAFAFA"
font = "sans serif"


[theme.dark]
primaryColor = "#2E7D32"
base = "dark"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[theme.light]
primaryColor = "#2E7D32"
base = "light"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#0E1117"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "auto"
showSidebarNavigation = false
